Bugfix/fix-sponsor-logo-scroll-not-working
TechUni2020/TechUni-hp pull request #59
Opened 2024-08-28 01:29 UTC by gohan5858

close #54

下の段のスクロールが一定量スライドすると止まってしまう不具合を修正
SlideContainer内のSliderItemの数が3個以下のであるとスライドが止まってしまうため4個以上にすることで対処
今回は1個増やすだけだとロゴの順番が崩れてしまうので元々のロゴ3個をそのまま複製しています

2024-08-29 20:28 UTC, KO1231 requested changes
依然SlideContainer内のslider-container-refのうち2個目([Source](https://github.com/TechUni2020/TechUni-hp/blob/4a542c2f79dfff56dd4bc1ba65cc2014bc8eb32b/src/components/Home/slider.jsx#L27-L34))がLogoSliderの右辺に来た瞬間止まってそう。確認してほしぃ
![image](https://github.com/user-attachments/assets/4c486fd6-49df-4165-9610-28ac7f88baef)
![image](https://github.com/user-attachments/assets/bd7a8698-d624-4745-a540-3639d6036c90)

2024-08-30 15:09 UTC, gohan5858 commented
こちらの環境だと1時間ほどローカルで立ち上げっぱなしにして検証してみても止まらへんのよね(-_-;)
そっちどんな感じで動かしてる？

2024-08-30 18:33 UTC, KO1231 commented
> こちらの環境だと1時間ほどローカルで立ち上げっぱなしにして検証してみても止まらへんのよね(-_-;) そっちどんな感じで動かしてる？

わかった気がする。画面の横長かな？
おそらく1”slider-container-ref-enabled”が完全に1"slider-container"外に出たら永遠にループされる実装になってる。

---

1920x1080のフルスクリーンで(おそらく環境によって多少の誤差あれど)、1296x190が1"slider-container"で
![image](https://github.com/user-attachments/assets/b6174363-fe26-4bc3-9bc8-63d50ff00be7)

現状1”slider-container-ref-enabled”が950x190やから、1296に対して950やからループせんのやとおもう
![image](https://github.com/user-attachments/assets/098b83d5-c615-4782-b2b8-4d7d8c2d68a2)

---

試しにそれぞれ要素数2倍にしたらいけた
![image](https://github.com/user-attachments/assets/f0ae2fa0-f65f-41ee-a91f-ae3ba81b585c)

2024-08-30 18:38 UTC, KO1231 commented
@gohan5858 
一応暫定で2倍にしてフルHDでも動作するやつここにpushした。
ただフルHDでは1"slider-container"の横長が1296やけど、4Kディスプレイとかで動作させたら伸びるやろうしおそらく同じ現象起こると思うから、理想は内部で計算させる実装をするのがいいかなと思う。
とりあえずissue解決でこのままマージしてもいいし、完全解決で内部計算実装してからマージしてもどっちでもいいと思う。

とりあえずissue解決の方やったらもっかいreview request飛ばしてもろて、完全解決目指す方向やったら内部実装終わったタイミングでreview request飛ばしてもろておねしゃす！

2024-08-30 19:18 UTC, gohan5858 commented
> @gohan5858 一応暫定で2倍にしてフルHDでも動作するやつここにpushした。 ただフルHDでは1"slider-container"の横長が1296やけど、4Kディスプレイとかで動作させたら横長も伸びるやろうで、おそらく同じ現象起こってまうと思うから、理想は内部で計算させる実装をするのがいいかなって感G
> 
> 携帯とかやったらまあ間違いなく横長大丈夫やろうし、PCでもフルHD環境orそれ以下の横長がほとんどやと思うから、
> 
> * とりあえずissue解決のためにこのままマージして、別issueとしてまた手空いたタイミングで内部計算のやつを実施
> * 完全解決目指して、内部計算実装してからマージ
>   のどっちでもいいと思うから選んでほC。
> 
> 前者やったらこのままもっかいreview request飛ばしてもろて、後者やったら内部実装終わったタイミングでreview request飛ばしてもらう感じでおねしゃす！

承知した
たまたま画像を無限スライドさせるcssに書き方見つけたからそれ試してみて無理そうやったらとりあえず一旦このままマージって感じにしようと思う

2024-08-30 19:21 UTC, KO1231 commented
> > @gohan5858 一応暫定で2倍にしてフルHDでも動作するやつここにpushした。 ただフルHDでは1"slider-container"の横長が1296やけど、4Kディスプレイとかで動作させたら横長も伸びるやろうで、おそらく同じ現象起こってまうと思うから、理想は内部で計算させる実装をするのがいいかなって感G
> > 携帯とかやったらまあ間違いなく横長大丈夫やろうし、PCでもフルHD環境orそれ以下の横長がほとんどやと思うから、
> > 
> > * とりあえずissue解決のためにこのままマージして、別issueとしてまた手空いたタイミングで内部計算のやつを実施
> > * 完全解決目指して、内部計算実装してからマージ
> >   のどっちでもいいと思うから選んでほC。
> > 
> > 前者やったらこのままもっかいreview request飛ばしてもろて、後者やったら内部実装終わったタイミングでreview request飛ばしてもらう感じでおねしゃす！
> 
> 承知した たまたま画像を無限スライドさせるcssに書き方見つけたからそれ試してみて無理そうやったらとりあえず一旦このままマージって感じにしようと思う

らじゃ！

2024-08-30 22:24 UTC, gohan5858 commented
@KO1231 

cssで書き換えていく中で見た目的にありかなっていうアニメーションできたから前の見比べてほしい
もし前と比べて見にくいとかあったら言ってもらえたら！
コード的なメリットは結構単純なcssで書けるから保守が楽そうっていうのがある
![sponsor_new_scroll_demo](https://github.com/user-attachments/assets/5a966039-e2c5-4ebc-8b40-40702854d79e)

2024-08-30 22:56 UTC, KO1231 commented on src/style.css
> +}
めっちゃいいと思う！！ 
ただめちゃ速度はやなってるから、ローカルで試した感じ10s -> 35~45sくらいに抑えるともっといいかも？
個人的には40くらいがちょうどいいかな～と思いつつ35s,45sくらいでもと思った(35~45のどこかはマジ好みやと思う)

2024-08-30 22:58 UTC, KO1231 commented on src/style.css
> +}
あと画像がでかくなってるのは想定？

2024-08-30 23:19 UTC, gohan5858 commented on src/style.css
> +}
速度の件、了解した
デバッグで早くしてた残りやわ申し訳
画像がデカくなってるのはおそらく現在のWindowの横幅基準で大きさ決めてるからかも、固定のほうがええかな？

2024-08-30 23:45 UTC, KO1231 commented on src/style.css
> +}
固定でもいいかも？ どっちにしろいまちょっとめちゃでかめなきがする

2024-09-02 20:21 UTC, gohan5858 commented on src/style.css
> +}
遅くなった申し訳ない🙇‍♂
サイズ調整完了した！
調整の兼ね合いでスライダー1個あたりのロゴ数を多くしたかったから、上下で繋がっている感じにしました
確認お願い！

2024-09-03 02:14 UTC, KO1231 commented on src/style.css
> +}
めっちゃよくなってる！！　あざす！！

2024-09-03 02:15 UTC, KO1231 approved these changes

2024-09-03 02:15 UTC, merged